" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
let mapleader=" "
syntax on
set number
set wrap  "change the column automatically"
set showcmd
set wildmenu  "tab "
set hlsearch "highlight"
exec "nohlsearch"
set incsearch "when put in the letter ,highlight"
"ignore the captial or small letter:set ignorecase,   set smartcase"


"the next and last find result,find:/+letter"
noremap = nzz   
noremap - Nzz  
"space + enter  :nohlsearch
noremap <LEADER><CR> :nohlsearch<CR>  
"left up down up*5 down*5"
noremap j h
noremap i k
noremap k j
noremap I 5k
noremap K 5j
"insert"
noremap n i
noremap N I
"html ctrl+y+,  ----> su
noremap <LEADER>y <C-y><C-,>
"save and quit,<CR> is enter"
map S :wq<CR>
map Q :q!<CR>
map s <nop>
map R :source $MYVIMRC<CR>
map ; :

"split
map si :set splitright<CR>:vsplit<CR>
map sn :set nosplitright<CR>:vsplit<CR>
map su :set no splitbelow<CR>:split<CR>
map se :set splitbelow<CR>:split<CR>
"change the window space+ijkl
map <LEADER>i <C-w>k
map <LEADER>j <C-w>h
map <LEADER>k <C-w>j
map <LEADER>l <C-w>l

"adjust each window size
map <up> :res+5<CR>
map <down> :res-5<CR>
map <left> :vertical resize-5<CR>
map <right> :vertical resize+5<CR>
"create new window
map tu :tabe<CR>
map tj :-tabnext<CR>
map tl :+tabnext<CR>
"change sub window vertical or horizontal
map sv <C-w>t<C-w>H
map sh <C-w>t<C-w>K
"insert ( { "  automatically )
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {}<Esc>i
inoremap " ""<Esc>i


"plugin
set nocompatible            
filetype off                  
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'mattn/emmet-vim'

call vundle#end()           
filetype plugin indent on   



"PLUG
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
"auto Complete
"Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'mattn/emmet-vim'
Plug 'scrooloose/nerdcommenter'

call plug#end()

execute pathogen#infect()



